CREATE TABLE IF NOT EXISTS "AdminReaperturasPrediccion" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PollaId" integer NOT NULL REFERENCES "Pollas"("Id") ON DELETE CASCADE,
    "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE CASCADE,
    "Fase" text NOT NULL,
    "Tipo" text NOT NULL,
    "Activa" boolean NOT NULL DEFAULT true,
    "AdminUsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE RESTRICT,
    "FechaCreacion" timestamp with time zone NOT NULL DEFAULT now(),
    "FechaActualizacion" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_AdminReaperturasPrediccion_PollaUsuarioFaseTipo"
ON "AdminReaperturasPrediccion" ("PollaId", "UsuarioId", "Fase", "Tipo");

CREATE INDEX IF NOT EXISTS "IX_AdminReaperturasPrediccion_Activas"
ON "AdminReaperturasPrediccion" ("PollaId", "UsuarioId", "Activa");
