CREATE TABLE IF NOT EXISTS "PollaInvitaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PollaId" integer NOT NULL REFERENCES "Pollas"("Id") ON DELETE CASCADE,
    "RemitenteId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE RESTRICT,
    "EmailInvitado" text NOT NULL,
    "Estado" text NOT NULL DEFAULT 'Pendiente',
    "FechaEnvio" timestamp with time zone NOT NULL DEFAULT now(),
    "UsuarioAceptadoId" integer NULL REFERENCES "Usuarios"("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_PollaInvitaciones_PollaId"
ON "PollaInvitaciones" ("PollaId");

CREATE INDEX IF NOT EXISTS "IX_PollaInvitaciones_EmailInvitado"
ON "PollaInvitaciones" ("EmailInvitado");
