CREATE TABLE IF NOT EXISTS "PasswordResetTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE CASCADE,
    "TokenHash" text NOT NULL,
    "ExpiraEn" timestamp with time zone NOT NULL,
    "Usado" boolean NOT NULL DEFAULT false,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_TokenHash"
ON "PasswordResetTokens" ("TokenHash");
