ALTER TABLE "Pollas"
ADD COLUMN IF NOT EXISTS "ValorInscripcion" numeric(12,2) NULL;

ALTER TABLE "Pollas"
ADD COLUMN IF NOT EXISTS "MetodoPago" text NULL;

ALTER TABLE "Usuarios"
ADD COLUMN IF NOT EXISTS "EmailConfirmado" boolean NOT NULL DEFAULT true;

ALTER TABLE "Usuarios"
ADD COLUMN IF NOT EXISTS "EmailConfirmadoEn" timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS "EmailVerificationTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE CASCADE,
    "TokenHash" text NOT NULL,
    "ExpiraEn" timestamp with time zone NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT now(),
    "Usado" boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS "IX_EmailVerificationTokens_TokenHash"
ON "EmailVerificationTokens" ("TokenHash");
