using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using WorldCup.Api.Data;
using WorldCup.Api.Services;

var builder = WebApplication.CreateBuilder(args);

// DbContext (Postgres)
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<AdminAuthorizationService>();
builder.Services.AddScoped<EmailService>();

// JWT
var jwt = builder.Configuration.GetSection("Jwt");
var key = Encoding.UTF8.GetBytes(jwt["Key"] ?? "SuperClaveTemporal123!");
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = false;
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwt["Issuer"],
        ValidAudience = jwt["Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(key)
    };
});

// Controllers + Swagger (forma compatible con .NET 8)
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "Pollas"
        ADD COLUMN IF NOT EXISTS "ValorInscripcion" numeric(12,2) NULL;

        ALTER TABLE "Pollas"
        ADD COLUMN IF NOT EXISTS "MetodoPago" text NULL;

        ALTER TABLE "Usuarios"
        ADD COLUMN IF NOT EXISTS "EmailConfirmado" boolean NOT NULL DEFAULT true;

        ALTER TABLE "Usuarios"
        ADD COLUMN IF NOT EXISTS "EmailConfirmadoEn" timestamp with time zone NULL;

        CREATE TABLE IF NOT EXISTS "EmailVerificationTokens" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE CASCADE,
            "TokenHash" text NOT NULL,
            "ExpiraEn" timestamp with time zone NOT NULL,
            "CreadoEn" timestamp with time zone NOT NULL DEFAULT now(),
            "Usado" boolean NOT NULL DEFAULT false
        );

        CREATE INDEX IF NOT EXISTS "IX_EmailVerificationTokens_TokenHash"
        ON "EmailVerificationTokens" ("TokenHash");

        CREATE TABLE IF NOT EXISTS "AdminReaperturasPrediccion" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PollaId" integer NOT NULL REFERENCES "Pollas"("Id") ON DELETE CASCADE,
            "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE CASCADE,
            "Fase" text NOT NULL,
            "Tipo" text NOT NULL,
            "Activa" boolean NOT NULL DEFAULT true,
            "AdminUsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id") ON DELETE RESTRICT,
            "FechaCreacion" timestamp with time zone NOT NULL DEFAULT now(),
            "FechaActualizacion" timestamp with time zone NOT NULL DEFAULT now()
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "UX_AdminReaperturasPrediccion_PollaUsuarioFaseTipo"
        ON "AdminReaperturasPrediccion" ("PollaId", "UsuarioId", "Fase", "Tipo");

        CREATE INDEX IF NOT EXISTS "IX_AdminReaperturasPrediccion_Activas"
        ON "AdminReaperturasPrediccion" ("PollaId", "UsuarioId", "Activa");
        """);
}

// middleware
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

// Swagger middleware (uso estándar en .NET 8)
app.UseSwagger();
app.UseSwaggerUI();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
